### ISSUE TITLE
LoL plugin continually creates fields inside debug view

### ISSUE THREAD

**Issue by Fib100** [sotano42/lol-api-c3-plugin#1]
# Problem
**Describe the bug**
The LoL plugin continually creates fields inside debug view of C3. This causes the entire debug game preview to be slow/unresponsive.

**Steps To Reproduce**
Steps to reproduce the behavior, be as detailed as possible:
1. Open the attached .c3p file
2. In C3 layout view, click "Debug Layout"
3. In the C3 debug preview window, click the LoL plugin link to view the debug fields
4. Observe that debug fields are being created continually

**Expected behavior**
The debug fields should be created one time.

## Attach a .c3p

[LoLPluginBug.zip](https://github.com/sotano42/lol-api-c3-plugin/files/5791821/LoLPluginBug.zip)

**Affected browsers/platforms:** 
Only tested it on Chrome version 87.0.4280.88 (Official Build) (64-bit)

**First affected release:** 
Using Construct 3 stable R225
Using v0.0.0.3 of the LoL plugin

## Stack Trace

No errors occur in browser.

**Screenshots**

## Hardware 

**Device (please complete the following information):**
 - Device: Lenovo Laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Comment by sotano42** [comment]
Bug has been confirmed, fix will be implemented in next release.

**Comment by sotano42** [comment]
Version 0.0.0.4 has been published. The bug was corrected, please update to the latest version.

**Comment by Fib100** [comment]
I just re-tested 0.0.0.4 and this same issue is still occurring. I"ve made sure I have the latest plugin installed in C3. Can we get this bug re-opened please?
![image](https://user-images.githubusercontent.com/1228708/105578972-6e551e80-5d49-11eb-80d0-3e92da192a3b.png)

**Comment by sotano42** [comment]
> I just re-tested 0.0.0.4 and this same issue is still occurring. I"ve made sure I have the latest plugin installed in C3. Can we get this bug re-opened please?
> ![image](https://user-images.githubusercontent.com/1228708/105578972-6e551e80-5d49-11eb-80d0-3e92da192a3b.png)

Hi, please make sure that "bundle addons" is turned off. It seems to me that your project is still using the old version, if bundled add-ons was turned on when saving.

See image below where the issue is corrected.
![image](https://user-images.githubusercontent.com/10860045/105903760-e770a200-5fe5-11eb-9b32-aa51a19d4b1c.png)
